### PR TITLE
lava: fix Lara getting set on fire on trapdoors over Lava

### LINKED ISSUE #2: OG bugfix: fix trapdoor setting you on fire
Current behavior:

Sometimes under rare circumstances jumping onto a drawbridge above a lava pit can cause Lara to catch on fire.

Desired behavior:

Lara doesn't catch fire.

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #2.

### CODE REVIEW

**Comment by walkawayy** [comment]
Lol I fixed the tilt lava issue, but didn't realize Lara is now setting on fire on the bridge again. o.o Made this a draft PR.

**Review by rr- — APPROVED** [review]

**Comment by rr-** [comment]
@walkawayy do we wait for #287 with 2.2? Doesn't sound like we'll be getting anywhere with that ticket.

**Comment by walkawayy** [comment]
I think we need more info on that one to solve it.

Also I have no clue how to solve the audio popping.

**Comment by rr-** [comment]
Yes, my point is that I think these can wait for 2.3 (or some other future version) and we can release 2.2 as-is.

**Comment by walkawayy** [comment]
Yep agreed.

**Pull request merged**
