### PR TITLE
demo: fix crash if user inputs during demo ring close

### LINKED ISSUE #264: OG Bug: Crash when pressing any button while demo mode is loading
In the main menu, wait for the demo to load. When the menu ring is closing to start demo mode press ctrl.

tombati crashes to desktop. T1M crashes with this error message
Screenshot 2021-12-10 232916

### PR DESCRIPTION
**Pull request by walkawayy**
Close #264.

### CODE REVIEW

**Review by oziphantom — APPROVED** [review]

**Review by rr- — APPROVED** [review]
Can you describe the nuances of this fix?

**Comment by walkawayy** [comment]
> Can you describe the nuances of this fix?
g_ResetFlag gets set to true after there's no user input for a while. This starts the ring closing animation. While that was happening, if the user pressed any button, the `if (g_InvMode != INV_TITLE_MODE || g_Input.any || g_InputDB.any) {` check was getting set to true, causing the `g_ResetFlag` to set to false. This is because the inventory loop ending condition of `} while (imo.status != RNG_DONE);` does not get set to done until the ring finishes closing.

So, once the loop finished and `` was no longer true, this check failed:
```
    if (g_ResetFlag) {
        return GF_START_DEMO;
    }
```
Then the game checks what item was chosen (nothing):
```
    switch (g_InvChosen) {
    case O_PASSPORT_OPTION:
```
so the case statement falls all the way to `return GF_NOP;` and the shell exits.

I was going to just make a `O_DEMO_OPTION` a case to check for in the `g_InvChosen` switch, but the `GAME_OBJECT_ID` enums are used in a bunch of places and there is a `O_NUMBER_OF = 191` cap, so adding to that didn't make sense.

**Comment by walkawayy** [comment]
I think I'm the only one who tested. But it's not like we have a lot of testers to help.

**Comment by rr-** [comment]
Worst case we'll get more bug reports, these seem easier to get a hold of…

**Pull request merged**
