### PR TITLE
savegame: fix pushables loading for legacy savegames

### LINKED ISSUE #536: Blocks no longer push-/pullable on legacy saves in v2.8
As @walkawayy had already found from someone posting on [TRF](https://www.tombraiderforums.com/showpost.php?p=8354495&postcount=271), it seems you can now no longer push or pull blocks when the loaded game stems from a legacy save.

1. Load a legacy save
2. Try to move a block

https://user-images.githubusercontent.com/4934209/166839142-fae2e449-da99-4291-847b-0a337388860e.mp4

Possible regression of #496 ?

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #536

### CODE REVIEW

**Comment by walkawayy** [comment]
Looks good. I can now move pushables from a legacy save. Is there any specific testing that needs done? I loaded a legacy save and can now move the blocks. After saving and reloading they still work, but new saves never had this issue.

**Comment by rr-** [comment]
If possible, you could test one legacy save from before, and one after a flipmap @walkawayy . Qualopec moving platforms would be a good place to test them.

**Comment by rr-** [comment]
Not really, no. The test for broken Bacon Lara should have no side effects.

**Comment by rr-** [comment]
Resolved conflicts.

**Comment by walkawayy** [comment]
LGTM

**Pull request merged**
