### PR TITLE
Add a game installer

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

For now this branch only demonstrates we can build GUI apps with .NET Core with our Docker toolchain. The .exe is just 7 KB, but needs .NET Runtime 3.5 which hopefully majority of the players have installed on their computers.

### CODE REVIEW

**Comment by rr-** [comment]
We still need an icon from @Richard-L but other than that the gist of it is ready for a review.

**Comment by Richard-L** [comment]
Was working on it last night but didn't finish. Tonight at a dinner party.... Hope the weekend will solve it. Very excited for this.

**Comment by walkawayy** [comment]
Great job!

I had to install [.NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore) where it says `Run desktop apps x64`.

I tested the TombATI install option which worked great. Here's what my T1M install folder looked like with all options selected:

image

We can craft some test scenarios like clean installs, upgrades, music, no music, UB, etc when the installer is fully done.

**Comment by Richard-L** [comment]
Yes please on scenarios! Good idea. Very very excited for this.

**Comment by rr-** [comment]
### Grab the installer from here

https://github.com/rr-/Tomb1Main/releases/tag/untagged-6dffb2e8cde8631ce568

### Testing scenarios

- Test on vanilla Steam installation
    - Should suggest downloading music
    - Should suggest downloading UB
    - Should find the game if it's installed
    - The target directory should contain the DATA and the FMV folders
    - The target directory should contain T1M files
    - Saves should not be copied since they're for a DOS version
- Test on vanilla GOG installation
    - Should suggest downloading music
    - Should suggest downloading UB
    - Should find the game if it's installed
    - The target directory should contain the DATA and the FMV folders
    - The target directory should contain T1M files
    - Saves should not be copied since they're for a DOS version
- Test on TombATI
    - Should NOT suggest downloading music
    - Should NOT suggest downloading UB
    - Should find the game only if
        - there is a C:\TombATI folder
        - in the Steam game's directory if it got installed there
        - or there is a desktop shortcut that can launch tombati. There are no other means to discover where it was installed.
    - The target directory should contain the DATA, the FMV and the music folders
    - The target directory should contain T1M files
    - The target directory should contain save files (and no HMI-something.386 despite numeric file extension)
- Test on Tomb1Main
    - Should NOT suggest downloading music
    - Should NOT suggest downloading UB
    - Should not find the game unless
        - The game was installed once. It creates a registry key HKEY_CURRENT_USER\Software\Tomb1Main\InstallPath to track this.
        - There exists a shortcut on the desktop to launch Tomb1Main.exe.
    - The target directory should keep all the files it has
    - The installation should override Tomb1Main.exe no matter whether the user chose to override the files.
      The other files (configuration etc.) should be overriden only if the user chooses to.

Apart from the `HKEY_CURRENT_USER\Software\Tomb1Main\InstallPath` registry key the installation is portable and as such we do not create an entry for appwiz.cpl to uninstall the game. The user can just delete the directory. After deleting the directory the installer should no longer find Tomb1Main installation, as it tests for tomb1main.exe's existence.

### Known things to be done

- A setting to launch the target folder after installation finishes (I think this should default to true)
- A setting to launch the game after installation finishes (I think this should default to false or maybe not add it)
- Currently Tomb1Main.exe is overwritten only if installing using the Tomb1Main source; I think this should always overwrite the .exe no matter the source since currently choosing Steam/GOG/TombATI but installing to a directory where the user previously installed Tomb1Main will result in the .exe not getting updated.
- Add an icon for the installer (posix to define it, the rest to agree on it)
- Possibly improve sidebar graphics. I'd use official TR art. Suggestions (don't mind the artifacts, I'll prepare more hires versions). I'm open to suggestions, but I'd like this to 1) not have boring background 2) 2:1 aspect ratio 3) no banner rotations or anything, just a single static image. We can use different images for each step though.

<table>
<tr>
<td>1<br/>TombRaider_01</td>
<td>2<br/>TombRaider_04</td>
</tr>
<tr>
<td>3<br/>TombRaider_11</td>
<td>4<br/>TombRaider_14</td>
</tr>
<tr>
<td>5<br/>TombRaider_24</td>
<td>6<br/>TombRaider_25</td>
</tr>
</table>

I think some of these are promo art for TR3, but I think it had the most renders with its launch. It's hard to come by some nice renders for TR1. The one I like the most is the image 3 and I think it fits with TR1 (Peru, even if the pyramid seems to be Aztec).

**Comment by Richard-L** [comment]
So amazing 👏👏👏

Can't wait to check this out and finally finish my graphics duties.

**Comment by Richard-L** [comment]
First experience running this on my work PC

image

Then after choosing to run anyway:
image
image

Then:
image

^ Takes you to: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore

I know all of these are pretty normal, but of course they'll scare off normal users, or they'll have no clue what to do about DOTnet. I suppose there's nothing we can do though to mitigate any of these, right?

**Comment by rr-** [comment]
I don't think we can, at least not unless we pay some ransom to Microsoft to license our .exes. I wouldn't mind if someone researched this topic; all I have is assumptions.

**Comment by walkawayy** [comment]
@rr- check these links out:

https://www.microsoft.com/en-us/wdsi/filesubmission
https://docs.microsoft.com/en-us/microsoft-365/security/intelligence/submission-guide?view=o365-worldwide
https://stackoverflow.com/questions/56544578/proper-way-of-releasing-software-and-creating-an-installer-for-it

**Comment by rr-** [comment]
The first two are when MS Defender labels our exe as a virus which is not the case. It just blocks it because it's not known.

The third link confirms I was right about $.
>Essentially you need to buy a Extended Validation Certificate to "buy trust" outright

I am not willing to do this and I don't want any contributor to waste their money on this. We build our .exes dynamically, who knows if a single byte difference will be enough for MS to say oh wow this is completely new exe, pay us again.

People who are willing to use this shit platform should deal with it.

https://stackoverflow.com/a/33505832

Re: .NET downloads. I am surprised it doesn't ship with the OS, but if it doesn't, there's not much we can do.
Apart from writing this in WinAPI in which case it will be not 2000 lines of code but 20 000. (Actually we'd need to replicate DiscUtils; make it 50 000.)

**Comment by walkawayy** [comment]
I agree about not paying. It sounds like if enough users safely use the installer, the Windows protection screen could resolve itself. Otherwise, users will have to use the `Run Anyway` option. Not much we can do about that.

I also had to install .NET. We could add instructions and a download link to the README since it seems Windows does not come with this by default.

I didn't get any antivirus errors (I only use Windows Defender), but it sounds like Avast was fine with the installer after a scan which doesn't seem bad.

**Comment by Richard-L** [comment]
@walkawayy @rr- @Rapora9 thoughts?

**Logo**

t1m-logo_curved-helvetica
-
t1m-logo_curved-trajan
-
t1m-logo_straight-trajan

**Icon**

16x16
32x32
48x48
64x64
128x128
256x256

^ not the proudest of these and has room for improvements.

I also tried generating an `.ICO` file of these rasters: [tomb1main-ico.zip](https://github.com/rr-/Tomb1Main/files/8895188/tomb1main.zip)

**Comment by Richard-L** [comment]
@rr- could run the installer now, some thoughts:

image
^ think you want more padding here, at least on the left.

image
^ top-align icon and source name at the same height
^ try removing the thin border (blue arrow), and work with padding and margin between items instead
^ there should be no scroll bar if the window is big enough for the list
^ do you think the (no folder selected) should itself become the button to click and change the path? I know this is just a status, but perhaps a 2-in-1 solution could be nice.
^ try giving "not found" the same font size as the description text since this is not a heading or name.

image
^ When a source has been found, the "Next" button should become clickable. Currently you need to first highlight a "found" source before it's possible to continue.

image
^ I would try a careful amount of padding/margin between the checkbox and description.
^ If TombATI was chosen and it's found the music data in it, you could list the files detected and no longer make people download from your server.

image
^ After selecting these options, I expected the install path to come _after_ the config. Then took me a while to find it above. Would want to suggest to move it down here.

image
^ I would go with a default OS progress bar instead of a custom one.

In the final screen where it says "happy raiding": I'm torn on the personal nature and emoji here. I would probably be more product-ish and just say "Installation process completed successfully". You could then also add info that the game features may be configured from /cfg JSONs.

image
^ The desktop shortcut created isn't a file shortcut. It's a URL shortcut for some reason. It's thus not possible to "open file location" on right-click. Any reason it's not a regular shortcut?
^ If the user has chosen to download UB, I would create a shortcut for it as well.

20220614_022133_Title
^ On a fresh game install, these savestates exist. Forgot to remove them? EDIT: Oh these were probably in my old TombATI folder and imported? I would add a checkbox per source "Import save states" that becomes clickable when it finds something.

**Comment by rr-** [comment]
Thanks for testing.

>think you want more padding here, at least on the left.

I'll consider this, but if you look at bottom right side, you'll see the margins are neat

>top-align icon and source name at the same height

The icon is centered vertically on purpose; I'll see if it looks better but if not I'll leave it as is

>try removing the thin border (blue arrow), and work with padding and margin between items instead

I'll consider this but I think then it'll be difficult for the user to discover that the items are clickable. I'll experiment.

>there should be no scroll bar if the window is big enough for the list

Agreed, not sure why it appears.

>do you think the (no folder selected) should itself become the button to click and change the path? I know this is just a status, but perhaps a 2-in-1 solution could be nice.

No, I think it would look silly.

>When a source has been found, the "Next" button should become clickable. Currently you need to first highlight a "found" source before it's possible to continue.

I'll try to default to selecting Tomb1Main, and if it's not available, default any of the "found" installations.

>I would try a careful amount of padding/margin between the checkbox and description.

That margin is controlled by the OS, I can't do much about it.

>If TombATI was chosen and it's found the music data in it, you could (...) no longer make people download from your server.

We copy the music files from TombATI, and the checkbox to download the music is disabled by default.

>If TombATI was chosen and it's found the music data in it, you could list the files detected and

Not sure where to put that list, plus if we wanted to let the user preview what the installer is going to create, I'd need to split the copy procedure into two steps: detect files, and copy files. This is not really possible with Steam and GOG without making the user wait until we extract the ISO file somewhere, before they can even install.

>After selecting these options, I expected the install path to come after the config. Then took me a while to find it above. Would want to suggest to move it down here.

OK, good point. I think it's caused by the visual heaviness of the download checkboxes.

>I would go with a default OS progress bar instead of a custom one.

That *is* a default OS progress bar, I didn't do any customization. Although I admit it's a bit uninspired. I was thinking about adding a console below what is being done, like in some installers (one that I know for sure was doing this was Winamp). WDYT?

>In the final screen where it says "happy raiding": I'm torn on the personal nature and emoji here. I would probably be more product-ish and just say "Installation process completed successfully". You could then also add info that the game features may be configured from /cfg JSONs.

This project is plenty soulless as it is, please let me have at least some resemblance of fun with it.

>The desktop shortcut created isn't a file shortcut. It's a URL shortcut for some reason. It's thus not possible to "open file location" on right-click. Any reason it's not a regular shortcut?

Yes – regular shortcuts [are rocket science](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-shllink/16cb4ca1-9339-4d0c-a68d-bf1d6cc0f943) and it's difficult to get them right. .NET 6 (our tech) does not really support them, you need to either roll your own code to create them or import some COM libraries that the toolchain complains about outside of Visual Studio (`IWshRuntimeLibrary`). On the other hand .URL shortcuts are just INI configuration files so it's trivial to write them.
That being said I'll try to write a .lnk file by hand.

>If the user has chosen to download UB, I would create a shortcut for it as well.

Good catch! I'll add that.

>I would add a checkbox per source "Import save states" that becomes clickable when it finds something

This really only applies to TombATI as we do not support DOS saves at all. Do you still want me to add a checkbox for it, that would only be visible for TombATI?

Can you let me know what you think about the sidebar images I posted above? The Caves screenshot is a WIP although I do admit it kinda fits.

>New logo

>Not the proudest of these

Well then I hope you won't hate me when I say this:

- The gradient looks weird. I thought you were going for a Metro UI flat appearance which the choice of a gradient contradicts.
- The glowing effect looks awesome, however it is downplayed by simple hexagon flat jewels. Lost opportunity there.
- Drop shadows look out of place.
- The choice is font in both variants is poor.
- Text placement – I don't think it should be under the Scion, instead it should be to its right and refer to the classic fonts – either TR1 or TR2-5.

I'd look for more inspiration. I'll try to hire a graphic designer some time next week to see what they can produce.

**Comment by Richard-L** [comment]
> I'll consider this but I think then it'll be difficult for the user to discover that the items are clickable. I'll experiment.

For classic desktop UX, "discoverability" would be handled through hover states. But I wasn't sure if this would go too far. The most basic hover states on Windows are simply different mouse cursors which changes from a pointer to a finger, hand, resizer, etc to signal intended interactivity.

> We copy the music files from TombATI, and the checkbox to download the music is disabled by default.

I don't think this was the case on my test. I used TombATI as source, and it still seemed to download music after.

> Not sure where to put that list, plus if we wanted to let the user preview what the installer is going to create, I'd need to split the copy procedure into two steps: detect files, and copy files. This is not really possible with Steam and GOG without making the user wait until we extract the ISO file somewhere, before they can even install.

I would actually love this a lot. A list of detected assets, and then a config where the user chooses the ones they want to use (although I'd put this inside a feature setup _after_ import). How long does your computer take to extract the GOG/Steam data? Is it long?
Handling it this way would allow the addition of more sources later, such as the PS1 disc for things like FMVs. I know I have a tendency to push against the scope of the installer, I hope you can still bear it lol.

> That _is_ a default OS progress bar, I didn't do any customization.

You know I don't think I've ever seen this narrow one in 25 years+ of using Windows :p

If you have control over it, I would do something like the top left. It seems a standard size for when windows wants to show a "thick" progress bar:
image

> I was thinking about adding a console below what is being done (...) WDYT?

Yes please!

Formatting idea:

`image` titleh.pcx …detected
`image` titleh.pcx (UB) …detected
`music` track-title.flac …detected
`level-files` LEVEL4.PHD …detected

etc

In fact I would like to stimulate an asset naming scheme. For example with music I'd love to see more semantic file names like:

00_ambiance_cave-echoes
01_ambiance_water
02_ambiance_wind
03_ambiance_heartbeat
04_soundtrack_main-theme-1
05_soundtrack_mysterious
06_soundtrack_main-theme-2
…
##_cutscene_lara-vs-larson
##_cutscene_the-hatching
…
##_voice_welcome-to-my-home
##_voice_aint-nothing-personal

^ all in concession of when they appear in the default gameflow. "Voice" could be further distinguished into "gym".

WDYT?

> This project is plenty soulless as it is

Whilst I think I know what you mean, I believe this is because so far we've not had the opportunity to do things for the public image. The installer will change that, and especially things like the 2:1 images you had in mind, which I think are a nice idea. I can try to produce some options for them.

> Yes – regular shortcuts are rocket science (..) That being said I'll try to write a .lnk file by hand.

That's annoying - I had no idea. Would path wildcards like %userprofile% or %programfiles% help at all, at least for cases where these paths are chosen? Probably not...

> This really only applies to TombATI as we do not support DOS saves at all. Do you still want me to add a checkbox for it, that would only be visible for TombATI?

I would say yes. It's an added convenience/feature, and good statement to the user that their savestates can be read by T1M. Do we not support GOG/Steam savestates? (Are they both DOS because Dosbox?)

> _Feedback on logo_

I kind of read between the lines you weren't a fan haha. You know I appreciate your honesty, and I mostly agree with you.
- The gradient can go. I just wanted to mimic the gradient on the original scion, but I'm happy to go flat design.
- I tried some effects on the jewels/medallions but they all looked bad. Didn't want to take another day on these (my time is just so limited...) and decided to show you as is. But yes, they should do something, I agree.
- Drop shadow can go, but text visibility on both dark and light background is a topic. You will need "some" outline I'm afraid.
- I also don't love the font. Curiously though I did trace the original TR1 logo font, and identified the word "TOMB" (the heavy sans serif font) as Helvetica. So I used that in one of them.
- Can place the text wherever we like, based on use scenario and available aspect to fill.

> I'll try to hire a graphic designer some time next week to see what they can produce.

Feel free, but it kind of makes me sad. Was really hoping I might actually be able to contribute something other than testing at least once...

**Comment by rr-** [comment]
>all in concession of when they appear in the default gameflow. "Voice" could be further distinguished into "gym".
>WDYT?

Sounds good but out of scope for this ticket/PR. I'm OK with adding a new ticket for it.

>I would actually love this a lot. A list of detected assets, and then a config where the user chooses the ones they want to use (although I'd put this inside a feature setup after import). How long does your computer take to extract the GOG/Steam data? Is it long? Handling it this way would allow the addition of more sources later, such as the PS1 disc for things like FMVs. 

Let's tackle this in a future iteration, for now we'll push the simpler variant.

>Do we not support GOG/Steam savestates? (Are they both DOS because Dosbox?)

Yes and yes; DOS saves are fundamentally different from TombATI's and neither TombATI or T1M ever supported them.

**Comment by Richard-L** [comment]
Just to add some image candidates. All of which would need a proper upscale + Photoshop tlc job:

cred3
cred4
demopic1
gym

Also I would only use TR1 renders or image assets, to keep it authentically TR1.

**Comment by rr-** [comment]
I like the first and the last GFX @Richard-L , can you clean them up?

**Comment by rr-** [comment]
Changes:

- Added a log console to the install step
- Added selection of Tomb1Main as the installation source by default, and if it's not available, any of the "found" sources
- Added a separate setting to import saves (shown only for T1M and TombATI)
- Added a setting to launch the target folder after installation finishes
- Added a setting to launch the game after installation finishes
- Added information that the game features may be configured from cfg/ JSONs
- Added creating a shortcut for the UB if it was found (looking for data/cat.phd)
- Changed the installer to make .lnk shortcuts instead of .url (this took six hours. we don't support non-ascii paths, Windows expects us to use DOS paths here. I'll need to find a workaround if this becomes a problem)
- Changed sidebar graphics (not final, I like posix's suggestions)
- Changed install step not to continue automatically (to give the user a chance to examine the installation logs)
- Changed change path buttons in the source step to hyperlinks
- Changed window padding to +2px
- Changed destination path selection placement to the bottom
- Changed progress bar height
- Changed "Finish" button text to "Close" in the last tab
- Fixed double margins in the installation settings tab
- Fixed destination path being clipped instead of having it end with an ellipsis if it's too long to fit in the window
- Fixed the scrollbar appearing even if there's enough room to render all sources
- Fixed a bug where installing T1M over itself and choosing to overwrite all files would result in an exception
- Removed useless introductory text in the installation settings tab, now that we need more space for the extra checkbox for the saves
- Removed useless introductory text in the installation progress tab, so that we do not repeat ourselves
- Removed the thin border in the source step in favor of padding

To do:
- Hire a graphic to make a logo
- Add an icon for the installer

Grab it here: https://github.com/rr-/Tomb1Main/releases/download/untagged-3f57295960905f1446d5/Tomb1Main-2.9.1-5-gfb2f482-Installer.exe

**Comment by Richard-L** [comment]
Wow massive changes, sounds amazing, and can't wait to try again.

I'm happy to give the two images a shot, but I'm travelling this weekend and won't have computer access until Monday evening. So can't promise anything until mid next week.

What resolution are we wanting?

**Comment by rr-** [comment]
The window is 640x480. It'd be nice to get the sidebar images at at least 300×600 (800×600 cropped to the 1:2 ratio); this number comes from the standard render resolution at the time the game were released. But my preference would be 400×800. More than that seems to only unnecessarily increase the installer .exe size as the graphics will be downscaled anyway.

**Comment by Richard-L** [comment]
Tried the new installer on my potato Win10 machine. It's crazy how slow the .NET download from Microsoft's server was, but eventually I had it. Speak of which, I saw this of someone bundling it into their release: https://github.com/IntelOrca/OpenLauncher/issues/2. Means of course the installer gets quite big. Is it to be considered? I would say OOBE is more important than small file size.

In any case, wow the UI changes make a big positive difference if you ask me. It feels much better now with the hovering here, better alignments, and padding:
image
^ not sure how interested you are, but you could experiment with the heading style of "Step 1: ..." to appear only once. It's usually good UI design practice. Steam, GOG, etc would probably be the same default body font size, but bold. The "not found" is a strong indicator already as it's red, so I'd suggest it doesn't need the heading size either. But keep it as you like better. The easiest solution would probably be to introduce a h2 style.
^ More importantly: If something is not detected, can you make it so that clicking on the entire block will launch the "change" dialogue? It doesn't make sense to signal it as one big button by hovering, when then you need to find the "change" span to actually click.
^ It also makes no sense to have an active state on the entries. You only need to click on them to interact = change source path.

image
^ If one source has been found like this and it's possible to continue, it shouldn't be necessary to select the source in question before the "next" button becomes clickable, especially if there's only one. Again, I would definitely lose :active states.

image
^ If I've chosen TombATI as a source, it should grey out the music download and indicate it's found music already. Maybe this behaviour can only happen later, just saying.
^ "Overwrite all existing files" could probably receive a small description text. I assume this is for updating TR1M at hand of the installer?
^ "Import saves" could perhaps receive something like: "Tomb1Main supports TombATI save states but not GOG/Steam. You may import them here." I'm actually curious if there is no way to convert DOS saves to become compatible. Could mean a decent bonus with GOG/Steam converts. If GOG/Steam are the found source, the save import should be greyed out. The description then helps to understand why.
^ The clean listing of the options now is beautiful.
^ Do you think there should perhaps be a < hr > before the "destination folder" setting? Feel it could help to distinguish it a bit as the last step of config.
^ If the user hits "back" at this stage, the previously found source is forgotten and has to be reassigned. Ideally it would remember.
^ It's a bit unfortunate there exist two styles of "change" buttons. Ideally there'd only be one across the installer. I prefer this latter one as it looks more like an actual button.

image
^ not super important, but if you can I'd either set a min-width on the installer window, or set it to hide the sidebar images after a certain breakpoint, should someone actually need the installer to be this narrow.
^ Also if someone does downsize and the window height isn't enough, a scrollbar should appear.

image
^ Since these are headings, experiment with minimal amount of margin here, or make the descriptions slightly smaller font. Latter is unadvisable for accessibility reasons though. I just think it would help to distinguish these headings from their descriptions stylistically. Again, h2? Could also make them bold, but I think entries without description will look a bit weird perhaps.

image
^ beautiful !

image
^ Also beautiful.
^ Consider losing the "Next" button here.
^ Is there any sense in allowing people to go back here? I suppose it would mean to unroll the installation just undertaken. I would probably just put a "close" button here.
^ Makes me think if we need to consider an uninstaller, or a process for it?

**Comment by rr-** [comment]
>It's crazy how slow the .NET download from Microsoft's server was, but eventually I had it.

Can't do much about it

>Speak of which, I saw this of someone bundling it into their release: IntelOrca/OpenLauncher#2. Means of course the installer gets quite big. Is it to be considered? I would say OOBE is more important than small file size.

It's 60+ megabytes. The game itself is 8. Sadly that is out of the question, the fans will be like WTF, and rightly so.

>experiment with the heading style of "Step 1: ..." to appear only once (...) introduce a h2 style.

That is already the case, the game titles are rendered at 15pt, and the header at 18pt.
I'll try to make it more visible

>More importantly: If something is not detected, can you make it so that clicking on the entire block will launch the "change" dialogue? It doesn't make sense to signal it as one big button by hovering, when then you need to find the "change" span to actually click.  
>It also makes no sense to have an active state on the entries. You only need to click on them to interact = change source path.  
>If one source has been found like this and it's possible to continue, it shouldn't be necessary to select the source in question before the "next" button becomes clickable, especially if there's only one. Again, I would definitely lose :active states.  

These suggestions make sense if we were to automatize the source selection entirely, however, I'm against this. I want the user to have the freedom to choose where they want to install the game from. Think about it: if you have ripped PSX files somewhere and a Steam installation, I think you would want to have the opportunity to select which files to go with rather than have the installer just select it for you and not even let you specify the folder. So the current UI will stay unless you can satisfy all these use cases:
- to be able to select a source by yourself
- to have it autodetected and not have to click anything
- to let change a path for a known source whose path otherwise was not detected.

>If I've chosen TombATI as a source, it should grey out the music download and indicate it's found music already. Maybe this behaviour can only happen later, just saying.

I'll do that

>"Overwrite all existing files" could probably receive a small description text. I assume this is for updating TR1M at hand of the installer?

It overwrites all existing files, including level files, music files, etc. Resets T1M to default. Otherwise the only file that gets always overwritten is Tomb1Main.exe; even the settings stay.
I'll add a small description.

>"Import saves" could perhaps receive something like: "Tomb1Main supports TombATI save states but not GOG/Steam. You may import them here." If GOG/Steam are the found source, the save import should be greyed out. The description then helps to understand why.

Makes sense, I'll do that

>I'm actually curious if there is no way to convert DOS saves to become compatible. Could mean a decent bonus with GOG/Steam converts. 

OK but later, not in this iteration

>Do you think there should perhaps be a < hr > before the "destination folder" setting? Feel it could help to distinguish it a bit as the last step of config.

I'll check how this looks

>If the user hits "back" at this stage, the previously found source is forgotten and has to be reassigned. Ideally it would remember.

Yeah, I know, it kinda resets to the default state. I'll see if I can do better.

>It's a bit unfortunate there exist two styles of "change" buttons. Ideally there'd only be one across the installer. I prefer this latter one as it looks more like an actual button.

I know however the hyperlink looks better in the source page (the button causes visual clutter) and the button looks better in the second page (a hyperlink makes this setting easy to miss). LMK what you think.

>set a min-width on the installer window

Yes, I'll do that

>set it to hide the sidebar images after a certain breakpoint

Also yes

>Also if someone does downsize and the window height isn't enough, a scrollbar should appear.

I'll do that

>Since these are headings, experiment with minimal amount of margin here, or make the descriptions slightly smaller font.

I'll go with a margin and a very slightly smaller font

>Consider losing the "Next" button here. (...) I would probably just put a "close" button here.

Makes sense, I'll do that

>Makes me think if we need to consider an uninstaller, or a process for it?

Nah. Apart from creating `HKEY_CURRENT_USER\Software\Tomb1Main\InstallPath` registry key storage of which takes like 0.1 kilobytes of disk space on the user machine, and two desktop shortcuts, the installation is fully portable, meaning we do not put random crap in the user's OS. They can just delete a folder. I can see people not understanding this and wanting to have an entry in the appwiz.cpl, but honestly this is a pain for me to support, so I'd wait until this actually gets reported by someone in the wild before putting resources into this.

**Comment by rr-** [comment]
Changes:

- Added a scrollbar if the installation settings are too small to fit
- Added a small description text to the "Overwrite all existing files" checkbox
- Added a small description text to the "Import saves" checkbox
- Added a separator above the target path
- Added accelerators to the back, next and close buttons (underscored letters that indicate you can press Alt+Letter to click it)
- Added a minimum width and height to the window
- Added hiding of the sidebar image if the window is too small (honestly this is overkill IMO)
- Changed the heading font from 18 pt to 20 pt to make it more outstanding (setting subheading to 14 pt made it too small)
- Changed the download checkboxes to grey out if the assets were already found
- Changed the Import Saves checkbox to grey out if its function is not supported, rather than hiding it completely
- Fixed going back resetting the selection and path settings
- Removed the Back and Next buttons on the final step

I didn't add margins to the checkbox hints as that was infeasible technically.

Grab it here: https://github.com/rr-/Tomb1Main/releases/download/untagged-2297c7d2d0156f619e2a/Tomb1Main-2.9.1-6-gcb15583-Installer.exe

**Comment by walkawayy** [comment]
The new version works great! All the window resizing works and the scrollbars update accordingly. I tested installing from TombATI and a T1M upgrade and didn't see any issues.

**Comment by kin37ik** [comment]
> ### Grab the installer from here
> 
> https://github.com/rr-/Tomb1Main/releases/tag/untagged-6dffb2e8cde8631ce568
> ### Testing scenarios
> 
>     * Test on vanilla Steam installation
>       
>       * Should suggest downloading music
>       * Should suggest downloading UB
>       * Should find the game if it's installed
>       * The target directory should contain the DATA and the FMV folders
>       * The target directory should contain T1M files
>       * Saves should not be copied since they're for a DOS version
> 
>     * Test on vanilla GOG installation
>       
>       * Should suggest downloading music
>       * Should suggest downloading UB
>       * Should find the game if it's installed
>       * The target directory should contain the DATA and the FMV folders
>       * The target directory should contain T1M files
>       * Saves should not be copied since they're for a DOS version
> 
>     * Test on TombATI
>       
>       * Should NOT suggest downloading music
>       * Should NOT suggest downloading UB
>       * Should find the game only if
>         
>         * there is a C:\TombATI folder
>         * in the Steam game's directory if it got installed there
>         * or there is a desktop shortcut that can launch tombati. There are no other means to discover where it was installed.
>       * The target directory should contain the DATA, the FMV and the music folders
>       * The target directory should contain T1M files
>       * The target directory should contain save files (and no HMI-something.386 despite numeric file extension)
> 
>     * Test on Tomb1Main
>       
>       * Should NOT suggest downloading music
>       * Should NOT suggest downloading UB
>       * Should not find the game unless
>         
>         * The game was installed once. It creates a registry key HKEY_CURRENT_USER\Software\Tomb1Main\InstallPath to track this.
>         * There exists a shortcut on the desktop to launch Tomb1Main.exe.
>       * The target directory should keep all the files it has
>       * The installation should override Tomb1Main.exe no matter whether the user chose to override the files.
>         The other files (configuration etc.) should be overriden only if the user chooses to.
> 
> 
> Apart from the `HKEY_CURRENT_USER\Software\Tomb1Main\InstallPath` registry key the installation is portable and as such we do not create an entry for appwiz.cpl to uninstall the game. The user can just delete the directory. After deleting the directory the installer should no longer find Tomb1Main installation, as it tests for tomb1main.exe's existence.
> ### Known things to be done
> 
>     * A setting to launch the target folder after installation finishes (I think this should default to true)
> 
>     * A setting to launch the game after installation finishes (I think this should default to false or maybe not add it)
> 
>     * Currently Tomb1Main.exe is overwritten only if installing using the Tomb1Main source; I think this should always overwrite the .exe no matter the source since currently choosing Steam/GOG/TombATI but installing to a directory where the user previously installed Tomb1Main will result in the .exe not getting updated.
> 
>     * Add an icon for the installer (posix to define it, the rest to agree on it)
> 
>     * Possibly improve sidebar graphics. I'd use official TR art. Suggestions (don't mind the artifacts, I'll prepare more hires versions). I'm open to suggestions, but I'd like this to 1) not have boring background 2) 2:1 aspect ratio 3) no banner rotations or anything, just a single static image. We can use different images for each step though.
> 
> 
> 1
> TombRaider_01 	2
> TombRaider_04
> 3
> TombRaider_11 	4
> TombRaider_14
> 5
> TombRaider_24 	6
> TombRaider_25
> 
> I think some of these are promo art for TR3, but I think it had the most renders with its launch. It's hard to come by some nice renders for TR1. The one I like the most is the image 3 and I think it fits with TR1 (Peru, even if the pyramid seems to be Aztec).

Hello

Posix said i should post here regarding the upscaling of these images.
Ive used an AI and accelerated the work with my GPU, i have zipped them up for you, i have used 2 different engines as results do vary a little bit so you have some choice, have attached the zip file for you.

If you need FMV's upscaled i can also do those.

Cheers
[laraupscalesNormEngine.zip](https://github.com/rr-/Tomb1Main/files/8933308/laraupscalesNormEngine.zip)
[laraupscalesAltEngine.zip](https://github.com/rr-/Tomb1Main/files/8933310/laraupscalesAltEngine.zip)
.

**Comment by Richard-L** [comment]
@rr- Would you want to add the standard TR1 PC retail CD, either physical or mounted, as a source?

I reckon you could almost trick it as a TombATI source if pointed to it?

**Comment by rr-** [comment]
Like we talked I'll consider this but I don't really plan on adding it in this cycle
I don't have a Tomb Raider CD and if it's the same as TombATI, you can point TombATI to look at D:\

**Comment by thekovic** [comment]
I tried the installer and it doesn't seem to be working for me. It just doesn't do anything, I get no window, no error message, I don't even see it in Task Manager. No idea what might be going on. .NET is installed.

**Comment by rr-** [comment]
Thank you Microsoft for good reliable technologies.

**Comment by walkawayy** [comment]
What OS are you on? @thekovic

**Comment by Richard-L** [comment]
> I like the first and the last GFX @Richard-L , can you clean them up?

Tried something. WDYT?


lara-standing
lara-swimming

The one of Lara standing from Saturn was just too low-res for any upscaler to do any good, so @kin37ik and I used [this one](https://core-design.com/images/goodies/tombraider/promotionalrenderstr1/screen56.jpg) instead.

The hairline is annoying on the first one. The banding on the second is quite strong so a good blur balance is not the most straightforward.

**Comment by thekovic** [comment]
@walkawayy Windows 10, 21H2

I compiled the installer myself from source and it works so probably the problem is on my side. Maybe some .NET runtime minor version difference voodoo.

Btw, after installing, is the folder not meant to contain Tomb1Main.exe (aka the installer doesn't ship Tomb1Main itself)?

**Comment by rr-** [comment]
>Btw, after installing, is the folder not meant to contain Tomb1Main.exe (aka the installer doesn't ship Tomb1Main itself)?

That happens if you do it from GH Actions, locally it contains just text.txt.

**Comment by rr-** [comment]
@Richard-L I'd prefer not to have plain white background graphics, fortunately there are plenty of options to choose from. Could you please reach consensus on discord what images should we go with and then post here final assets to include? I wouldn't like the discussion here to center around the images as they're not that important.

**Pull request merged**
