### PR TITLE
Make anisotropy filter value configurable

### PR DESCRIPTION
**Pull request by rr-**
The motivation for this PR has two sources:

- TombATI makes it possible to change the anisotropy filter value
- I am facing a problem on wine that makes the game unplayable if there are many textures and the anisotropy filter is enabled

### CODE REVIEW

**Comment by walkawayy** [comment]
I tested this in Caves, and the wolf tracks look a lot better with anisotropic filtering. However, there are now black line artifacts between the floor textures that seem to show up. I merged in the Vbuf fidelity to see if that was needed to fix it, but it's still there. Here's some screenshots. Look at the white floor in the distance with the filter on. There's like black dashing lines. It's really obvious in motion.

Here's a filter value of 0:
screenshot0003


Here's a filter value of 16.0:
screenshot0000

**Comment by walkawayy** [comment]
I zoomed in to make it more obvious. This is with the 16 filter on:
image

**Comment by rr-** [comment]
@walkawayy are you saying that #285 breaks the anisotropic filter?
I agree that disabling the filter looks worse; my only motivation for this PR  is to let me play the game on Wine, because without this fix the game runs at 1 frame per minute…

**Comment by walkawayy** [comment]
Hmm you're right. The issue is present on master. I must not have noticed before and only noticed because I was looking for the filtering? Would the fix you applied to the walls having this issue work for the floors too?

Seems like this PR is good then.

**Review by walkawayy — APPROVED** [review]

**Comment by rr-** [comment]
>BTW: Does this make the perspective setting from the sunglasses in the menu work?

No :D that is hardcoded and it makes sense to do so, because who would want to watch the textures morph? But Ialready have plans on what to put there instead :)

**Pull request merged**
