### PR TITLE
savegame: fix loading legacy Evil Lara

### LINKED ISSUE #261: Bug: Atlantis save files incompatible between T1M and Tombati
Using a save file for Atlantis created in tombati causes a crash in Tomb1Main and vice versa.
Tried my own saves, and saves downloaded from Stella's website.

The rest of the levels' save files seem to work normally.

### PR DESCRIPTION
**Pull request by rr-**
Closes #261

### CODE REVIEW

**Comment by rr-** [comment]
@walkawayy can I have some reviews and testing? Then we'll release 2.1 if it's good

**Comment by walkawayy** [comment]
I loaded a TombATI save before the Evil Lara room, went in the room and killed the two other mutants, then saved. When I tried to reload, the game crashed.

**Comment by rr-** [comment]
I can't continue this pull request because an update to wine made T1M no longer run on my system.

**Comment by rr-** [comment]
@walkawayy actually I can run the game if I completely disable texturing. I spotted and bug and fixed it. The bug was quite blatant, I wasn't checking for `flags & SAVE_CREATURE`. let me know if it's OK now.

**Comment by walkawayy** [comment]
Alright now this worked for me! I loaded a TombATI save, spawned Evil Lara, ran around and played with Dozy, saved, reloaded, did some more playing around, and everything worked.

**Pull request merged**
