### PR TITLE
inv: add T1M version in the corner

### PR DESCRIPTION
**Pull request by rr-**

### CODE REVIEW

**Comment by thatguyfrombb** [comment]
`make docker_build` is throwing this:
```
Traceback (most recent call last):
  File "scripts/generate_version", line 27, in <module>
    main()
  File "scripts/generate_version", line 17, in main
    with (SRC_DIR / "version.c").open("w") as handle:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'src/version.c'
make: *** [Makefile:42: autogenerated_version] Error 1
make: *** [Makefile:68: docker_build] Error 2
```

**Comment by rr-** [comment]
It's the same issue that we had with `init.c`, fixed.

**Comment by thatguyfrombb** [comment]
Got this:
```
The command '/bin/sh -c chmod 0666 /app/src/version.c' returned a non-zero code: 1
make: *** [Makefile:65: docker] Error 1
```
Adding a `RUN touch /app/src/version.c` caused this:
```
/usr/bin/i686-w64-mingw32-ld: build/src/game/inventry.o:inventry.c:(.text+0x1adb): undefined reference to `T1MVersion'
collect2: error: ld returned 1 exit status
make: *** [Makefile:20: build] Error 1
make: *** [Makefile:68: docker_build] Error 2
```
Tried changing the Dockerfile to run `make autogenerated_version`, but it didn't output anything outside the container (even if I touched the file from the shell), so I edited the Makefile to add the whole `src` folder. Maybe ugly, got it building.

**Review by thatguyfrombb — CHANGES_REQUESTED** [review]
Both testing and code look good, but it still breaks docker_build. I think GH release should work OK, but I'd prefer to fix the build system first.

**Comment by thatguyfrombb** [comment]
Also, just so I can set my priorities straight, only this PR makes it to v1.3.0, right? We don't care if other stuff like shotgun makes it today, yeah?

**Comment by rr-** [comment]
Yes

**Comment by rr-** [comment]
I can't reproduce the issue @thatguyfrombb 
```console
rr-@lightning:~/work/priv/Tomb1Main(version)$ make clean
find build -type f -iname '*.o' -delete
find build -type f -iname '*.dll' -delete
rm -f build/version.res build/version.rc
find . -type d -empty -delete

rr-@lightning:~/work/priv/Tomb1Main(version)$ make docker_build
docker build -t tomb1main .
Sending build context to Docker daemon  53.23MB
Step 1/8 : FROM ubuntu:latest
 ---> 597ce1600cf4
Step 2/8 : RUN apt-get update &&     apt-get upgrade -y &&     apt-get install -y gcc-mingw-w64-i686 make git python3-pip &&     python3 -m pip install pyjson5
 ---> Using cache
 ---> b5188eb0f2f8
Step 3/8 : RUN mkdir /app
 ---> Using cache
 ---> 69858761839e
Step 4/8 : ADD . /app
 ---> 718263624917
Step 5/8 : WORKDIR /app
 ---> Running in 7eaf336bfa5c
Removing intermediate container 7eaf336bfa5c
 ---> bf0f7fec69ac
Step 6/8 : RUN chmod 0666 /app/src/init.c
 ---> Running in a702f2c06025
Removing intermediate container a702f2c06025
 ---> 0e0d19b1238d
Step 7/8 : RUN chmod 0666 /app/src/version.c
 ---> Running in 40651a874541
Removing intermediate container 40651a874541
 ---> c74ebba00705
Step 8/8 : CMD ["make", "build"]
 ---> Running in 8a1c0962414e
Removing intermediate container 8a1c0962414e
 ---> 3376f1d04c59
Successfully built 3376f1d04c59
Successfully tagged tomb1main:latest
docker run --rm \
        --user 1000:1000 \
        -v /home/rr-/work/priv/Tomb1Main/.git:/app/.git \
        -v /home/rr-/work/priv/Tomb1Main/build:/app/build \
        tomb1main
i686-w64-mingw32-gcc -Wall -Isrc -c "src/filesystem.c" -o "build/src/filesystem.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/global/vars_platform.c" -o "build/src/global/vars_platform.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/global/vars.c" -o "build/src/global/vars.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/main.c" -o "build/src/main.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/json.c" -o "build/src/json.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/version.c" -o "build/src/version.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/ati.c" -o "build/src/specific/ati.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/file.c" -o "build/src/specific/file.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/sndpc.c" -o "build/src/specific/sndpc.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/clock.c" -o "build/src/specific/clock.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/output.c" -o "build/src/specific/output.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/input.c" -o "build/src/specific/input.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/shell.c" -o "build/src/specific/shell.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/hwr.c" -o "build/src/specific/hwr.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/smain.c" -o "build/src/specific/smain.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/display.c" -o "build/src/specific/display.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/frontend.c" -o "build/src/specific/frontend.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/specific/init.c" -o "build/src/specific/init.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/inject.c" -o "build/src/inject.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/dynarray.c" -o "build/src/dynarray.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/log.c" -o "build/src/log.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/3dsystem/phd_math.c" -o "build/src/3dsystem/phd_math.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/3dsystem/scalespr.c" -o "build/src/3dsystem/scalespr.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/3dsystem/3d_gen.c" -o "build/src/3dsystem/3d_gen.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/args.c" -o "build/src/args.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/config.c" -o "build/src/config.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/option.c" -o "build/src/game/option.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/laraswim.c" -o "build/src/game/laraswim.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/inventry.c" -o "build/src/game/inventry.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/cabin.c" -o "build/src/game/objects/cabin.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/pickup.c" -o "build/src/game/objects/pickup.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/door.c" -o "build/src/game/objects/door.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/puzzle_hole.c" -o "build/src/game/objects/puzzle_hole.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/keyhole.c" -o "build/src/game/objects/keyhole.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/misc.c" -o "build/src/game/objects/misc.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/boat.c" -o "build/src/game/objects/boat.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/bridge.c" -o "build/src/game/objects/bridge.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/trapdoor.c" -o "build/src/game/objects/trapdoor.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/switch.c" -o "build/src/game/objects/switch.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/cog.c" -o "build/src/game/objects/cog.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/scion.c" -o "build/src/game/objects/scion.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/savegame_crystal.c" -o "build/src/game/objects/savegame_crystal.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/objects/gunshot.c" -o "build/src/game/objects/gunshot.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/lot.c" -o "build/src/game/lot.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/camera.c" -o "build/src/game/camera.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/collide.c" -o "build/src/game/collide.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/demo.c" -o "build/src/game/demo.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/sound.c" -o "build/src/game/sound.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/mnsound.c" -o "build/src/game/mnsound.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/text.c" -o "build/src/game/text.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/hair.c" -o "build/src/game/hair.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/sphere.c" -o "build/src/game/sphere.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/larafire.c" -o "build/src/game/larafire.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/pause.c" -o "build/src/game/pause.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/items.c" -o "build/src/game/items.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/control.c" -o "build/src/game/control.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/larasurf.c" -o "build/src/game/larasurf.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/lara.c" -o "build/src/game/lara.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/invvars.c" -o "build/src/game/invvars.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/lara1gun.c" -o "build/src/game/lara1gun.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/lara2gun.c" -o "build/src/game/lara2gun.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/pod.c" -o "build/src/game/ai/pod.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/skate_kid.c" -o "build/src/game/ai/skate_kid.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/centaur.c" -o "build/src/game/ai/centaur.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/larson.c" -o "build/src/game/ai/larson.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/lion.c" -o "build/src/game/ai/lion.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/raptor.c" -o "build/src/game/ai/raptor.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/rat.c" -o "build/src/game/ai/rat.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/bat.c" -o "build/src/game/ai/bat.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/cowboy.c" -o "build/src/game/ai/cowboy.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/statue.c" -o "build/src/game/ai/statue.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/natla.c" -o "build/src/game/ai/natla.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/mummy.c" -o "build/src/game/ai/mummy.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/mutant.c" -o "build/src/game/ai/mutant.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/wolf.c" -o "build/src/game/ai/wolf.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/bear.c" -o "build/src/game/ai/bear.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/evil_lara.c" -o "build/src/game/ai/evil_lara.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/abortion.c" -o "build/src/game/ai/abortion.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/vole.c" -o "build/src/game/ai/vole.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/ape.c" -o "build/src/game/ai/ape.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/pierre.c" -o "build/src/game/ai/pierre.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/dino.c" -o "build/src/game/ai/dino.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/crocodile.c" -o "build/src/game/ai/crocodile.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/baldy.c" -o "build/src/game/ai/baldy.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/ai/alligator.c" -o "build/src/game/ai/alligator.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/invfunc.c" -o "build/src/game/invfunc.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/savegame.c" -o "build/src/game/savegame.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/overlay.c" -o "build/src/game/overlay.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/twinkle.c" -o "build/src/game/effects/twinkle.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/flood.c" -o "build/src/game/effects/flood.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/flicker.c" -o "build/src/game/effects/flicker.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/turn_180.c" -o "build/src/game/effects/turn_180.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/lara_effects.c" -o "build/src/game/effects/lara_effects.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/waterfall.c" -o "build/src/game/effects/waterfall.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/splash.c" -o "build/src/game/effects/splash.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/explosion.c" -o "build/src/game/effects/explosion.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/ricochet.c" -o "build/src/game/effects/ricochet.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/earthquake.c" -o "build/src/game/effects/earthquake.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/dino_stomp.c" -o "build/src/game/effects/dino_stomp.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/raising_block.c" -o "build/src/game/effects/raising_block.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/flipmap.c" -o "build/src/game/effects/flipmap.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/sand.c" -o "build/src/game/effects/sand.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/finish_level.c" -o "build/src/game/effects/finish_level.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/blood.c" -o "build/src/game/effects/blood.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/chain_block.c" -o "build/src/game/effects/chain_block.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/powerup.c" -o "build/src/game/effects/powerup.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/body_part.c" -o "build/src/game/effects/body_part.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/missile.c" -o "build/src/game/effects/missile.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/bubble.c" -o "build/src/game/effects/bubble.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/effects/stairs2slope.c" -o "build/src/game/effects/stairs2slope.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/draw.c" -o "build/src/game/draw.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/laramisc.c" -o "build/src/game/laramisc.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/game.c" -o "build/src/game/game.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/requester.c" -o "build/src/game/requester.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/gameflow.c" -o "build/src/game/gameflow.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/settings.c" -o "build/src/game/settings.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/setup.c" -o "build/src/game/setup.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/cinema.c" -o "build/src/game/cinema.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/teeth_trap.c" -o "build/src/game/traps/teeth_trap.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/spikes.c" -o "build/src/game/traps/spikes.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/falling_block.c" -o "build/src/game/traps/falling_block.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/movable_block.c" -o "build/src/game/traps/movable_block.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/dart.c" -o "build/src/game/traps/dart.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/lava.c" -o "build/src/game/traps/lava.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/thors_hammer.c" -o "build/src/game/traps/thors_hammer.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/midas_touch.c" -o "build/src/game/traps/midas_touch.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/lightning_emitter.c" -o "build/src/game/traps/lightning_emitter.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/rolling_ball.c" -o "build/src/game/traps/rolling_ball.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/flame.c" -o "build/src/game/traps/flame.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/dart_emitter.c" -o "build/src/game/traps/dart_emitter.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/damocles_sword.c" -o "build/src/game/traps/damocles_sword.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/falling_ceiling.c" -o "build/src/game/traps/falling_ceiling.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/pendulum.c" -o "build/src/game/traps/pendulum.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/traps/rolling_block.c" -o "build/src/game/traps/rolling_block.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/box.c" -o "build/src/game/box.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/game/people.c" -o "build/src/game/people.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/inject_util.c" -o "build/src/inject_util.o"
i686-w64-mingw32-gcc -Wall -Isrc -c "src/init.c" -o "build/src/init.o"
sed s/{version}/1.2.2-239-g2a76f6d/g src/version.rc >build/version.rc
i686-w64-mingw32-windres build/version.rc -O coff -o build/version.res
python3 scripts/generate_version
python3 scripts/generate_init
i686-w64-mingw32-gcc -Wall -Isrc  build/src/filesystem.o  build/src/global/vars_platform.o  build/src/global/vars.o  build/src/main.o  build/src/json.o  build/src/version.o  build/src/specific/ati.o  build/src/specific/file.o  build/src/specific/sndpc.o  build/src/specific/clock.o  build/src/specific/output.o  build/src/specific/input.o  build/src/specific/shell.o  build/src/specific/hwr.o  build/src/specific/smain.o  build/src/specific/display.o  build/src/specific/frontend.o  build/src/specific/init.o  build/src/inject.o  build/src/dynarray.o  build/src/log.o  build/src/3dsystem/phd_math.o  build/src/3dsystem/scalespr.o  build/src/3dsystem/3d_gen.o  build/src/args.o  build/src/config.o  build/src/game/option.o  build/src/game/laraswim.o  build/src/game/inventry.o  build/src/game/objects/cabin.o  build/src/game/objects/pickup.o  build/src/game/objects/door.o  build/src/game/objects/puzzle_hole.o  build/src/game/objects/keyhole.o  build/src/game/objects/misc.o  build/src/game/objects/boat.o  build/src/game/objects/bridge.o  build/src/game/objects/trapdoor.o  build/src/game/objects/switch.o  build/src/game/objects/cog.o  build/src/game/objects/scion.o  build/src/game/objects/savegame_crystal.o  build/src/game/objects/gunshot.o  build/src/game/lot.o  build/src/game/camera.o  build/src/game/collide.o  build/src/game/demo.o  build/src/game/sound.o  build/src/game/mnsound.o  build/src/game/text.o  build/src/game/hair.o  build/src/game/sphere.o  build/src/game/larafire.o  build/src/game/pause.o  build/src/game/items.o  build/src/game/control.o  build/src/game/larasurf.o  build/src/game/lara.o  build/src/game/invvars.o  build/src/game/lara1gun.o  build/src/game/lara2gun.o  build/src/game/ai/pod.o  build/src/game/ai/skate_kid.o  build/src/game/ai/centaur.o  build/src/game/ai/larson.o  build/src/game/ai/lion.o  build/src/game/ai/raptor.o  build/src/game/ai/rat.o  build/src/game/ai/bat.o  build/src/game/ai/cowboy.o  build/src/game/ai/statue.o  build/src/game/ai/natla.o  build/src/game/ai/mummy.o  build/src/game/ai/mutant.o  build/src/game/ai/wolf.o  build/src/game/ai/bear.o  build/src/game/ai/evil_lara.o  build/src/game/ai/abortion.o  build/src/game/ai/vole.o  build/src/game/ai/ape.o  build/src/game/ai/pierre.o  build/src/game/ai/dino.o  build/src/game/ai/crocodile.o  build/src/game/ai/baldy.o  build/src/game/ai/alligator.o  build/src/game/invfunc.o  build/src/game/savegame.o  build/src/game/overlay.o  build/src/game/effects/twinkle.o  build/src/game/effects/flood.o  build/src/game/effects/flicker.o  build/src/game/effects/turn_180.o  build/src/game/effects/lara_effects.o  build/src/game/effects/waterfall.o  build/src/game/effects/splash.o  build/src/game/effects/explosion.o  build/src/game/effects/ricochet.o  build/src/game/effects/earthquake.o  build/src/game/effects/dino_stomp.o  build/src/game/effects/raising_block.o  build/src/game/effects/flipmap.o  build/src/game/effects/sand.o  build/src/game/effects/finish_level.o  build/src/game/effects/blood.o  build/src/game/effects/chain_block.o  build/src/game/effects/powerup.o  build/src/game/effects/body_part.o  build/src/game/effects/missile.o  build/src/game/effects/bubble.o  build/src/game/effects/stairs2slope.o  build/src/game/draw.o  build/src/game/laramisc.o  build/src/game/game.o  build/src/game/requester.o  build/src/game/gameflow.o  build/src/game/settings.o  build/src/game/setup.o  build/src/game/cinema.o  build/src/game/traps/teeth_trap.o  build/src/game/traps/spikes.o  build/src/game/traps/falling_block.o  build/src/game/traps/movable_block.o  build/src/game/traps/dart.o  build/src/game/traps/lava.o  build/src/game/traps/thors_hammer.o  build/src/game/traps/midas_touch.o  build/src/game/traps/lightning_emitter.o  build/src/game/traps/rolling_ball.o  build/src/game/traps/flame.o  build/src/game/traps/dart_emitter.o  build/src/game/traps/damocles_sword.o  build/src/game/traps/falling_ceiling.o  build/src/game/traps/pendulum.o  build/src/game/traps/rolling_block.o  build/src/game/box.o  build/src/game/people.o  build/src/inject_util.o  build/src/init.o build/version.res -ldbghelp -lwinmm -ldsound -lddraw -ldinput8 -ldxguid -static -shared -o build/Tomb1Main.dll
```

**Comment by rr-** [comment]
Updated, instead of generating a new non-versioned file with a hardcoded variable, I came up with using a define and providing a fallback define in case nobody supplied the right version.

**Review by thatguyfrombb — APPROVED** [review]

**Pull request merged**
